#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL_DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DAMN_CuaHangThucAnNhanh")]
	public partial class dataQLKhachHangDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertQL_KHACHHANG(QL_KHACHHANG instance);
    partial void UpdateQL_KHACHHANG(QL_KHACHHANG instance);
    partial void DeleteQL_KHACHHANG(QL_KHACHHANG instance);
    partial void InsertQL_ChiTietHoaDon(QL_ChiTietHoaDon instance);
    partial void UpdateQL_ChiTietHoaDon(QL_ChiTietHoaDon instance);
    partial void DeleteQL_ChiTietHoaDon(QL_ChiTietHoaDon instance);
    partial void InsertQL_HoaDon_BanHang(QL_HoaDon_BanHang instance);
    partial void UpdateQL_HoaDon_BanHang(QL_HoaDon_BanHang instance);
    partial void DeleteQL_HoaDon_BanHang(QL_HoaDon_BanHang instance);
    partial void InsertQL_LoaiSanPham(QL_LoaiSanPham instance);
    partial void UpdateQL_LoaiSanPham(QL_LoaiSanPham instance);
    partial void DeleteQL_LoaiSanPham(QL_LoaiSanPham instance);
    partial void InsertQL_SanPham(QL_SanPham instance);
    partial void UpdateQL_SanPham(QL_SanPham instance);
    partial void DeleteQL_SanPham(QL_SanPham instance);
    partial void InsertQL_NguoiDung(QL_NguoiDung instance);
    partial void UpdateQL_NguoiDung(QL_NguoiDung instance);
    partial void DeleteQL_NguoiDung(QL_NguoiDung instance);
    #endregion
		
		public dataQLKhachHangDataContext() : 
				base(global::BLL_DAL.Properties.Settings.Default.DAMN_CuaHangThucAnNhanhConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public dataQLKhachHangDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dataQLKhachHangDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dataQLKhachHangDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dataQLKhachHangDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<QL_KHACHHANG> QL_KHACHHANGs
		{
			get
			{
				return this.GetTable<QL_KHACHHANG>();
			}
		}
		
		public System.Data.Linq.Table<QL_ChiTietHoaDon> QL_ChiTietHoaDons
		{
			get
			{
				return this.GetTable<QL_ChiTietHoaDon>();
			}
		}
		
		public System.Data.Linq.Table<QL_HoaDon_BanHang> QL_HoaDon_BanHangs
		{
			get
			{
				return this.GetTable<QL_HoaDon_BanHang>();
			}
		}
		
		public System.Data.Linq.Table<QL_LoaiSanPham> QL_LoaiSanPhams
		{
			get
			{
				return this.GetTable<QL_LoaiSanPham>();
			}
		}
		
		public System.Data.Linq.Table<QL_SanPham> QL_SanPhams
		{
			get
			{
				return this.GetTable<QL_SanPham>();
			}
		}
		
		public System.Data.Linq.Table<QL_NguoiDung> QL_NguoiDungs
		{
			get
			{
				return this.GetTable<QL_NguoiDung>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QL_KHACHHANG")]
	public partial class QL_KHACHHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _SDT;
		
		private string _HoTen;
		
		private string _CMND;
		
		private System.Nullable<int> _DiemSo;
		
		private EntitySet<QL_HoaDon_BanHang> _QL_HoaDon_BanHangs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnDiemSoChanging(System.Nullable<int> value);
    partial void OnDiemSoChanged();
    #endregion
		
		public QL_KHACHHANG()
		{
			this._QL_HoaDon_BanHangs = new EntitySet<QL_HoaDon_BanHang>(new Action<QL_HoaDon_BanHang>(this.attach_QL_HoaDon_BanHangs), new Action<QL_HoaDon_BanHang>(this.detach_QL_HoaDon_BanHangs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="NVarChar(50)")]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemSo", DbType="Int")]
		public System.Nullable<int> DiemSo
		{
			get
			{
				return this._DiemSo;
			}
			set
			{
				if ((this._DiemSo != value))
				{
					this.OnDiemSoChanging(value);
					this.SendPropertyChanging();
					this._DiemSo = value;
					this.SendPropertyChanged("DiemSo");
					this.OnDiemSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_KHACHHANG_QL_HoaDon_BanHang", Storage="_QL_HoaDon_BanHangs", ThisKey="SDT", OtherKey="SDT")]
		public EntitySet<QL_HoaDon_BanHang> QL_HoaDon_BanHangs
		{
			get
			{
				return this._QL_HoaDon_BanHangs;
			}
			set
			{
				this._QL_HoaDon_BanHangs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QL_HoaDon_BanHangs(QL_HoaDon_BanHang entity)
		{
			this.SendPropertyChanging();
			entity.QL_KHACHHANG = this;
		}
		
		private void detach_QL_HoaDon_BanHangs(QL_HoaDon_BanHang entity)
		{
			this.SendPropertyChanging();
			entity.QL_KHACHHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QL_ChiTietHoaDon")]
	public partial class QL_ChiTietHoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHD;
		
		private string _MaSP;
		
		private System.Nullable<int> _Soluong;
		
		private System.Nullable<int> _DonGia;
		
		private EntityRef<QL_HoaDon_BanHang> _QL_HoaDon_BanHang;
		
		private EntityRef<QL_SanPham> _QL_SanPham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHDChanging(string value);
    partial void OnMaHDChanged();
    partial void OnMaSPChanging(string value);
    partial void OnMaSPChanged();
    partial void OnSoluongChanging(System.Nullable<int> value);
    partial void OnSoluongChanged();
    partial void OnDonGiaChanging(System.Nullable<int> value);
    partial void OnDonGiaChanged();
    #endregion
		
		public QL_ChiTietHoaDon()
		{
			this._QL_HoaDon_BanHang = default(EntityRef<QL_HoaDon_BanHang>);
			this._QL_SanPham = default(EntityRef<QL_SanPham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHD", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHD
		{
			get
			{
				return this._MaHD;
			}
			set
			{
				if ((this._MaHD != value))
				{
					if (this._QL_HoaDon_BanHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHDChanging(value);
					this.SendPropertyChanging();
					this._MaHD = value;
					this.SendPropertyChanged("MaHD");
					this.OnMaHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSP", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSP
		{
			get
			{
				return this._MaSP;
			}
			set
			{
				if ((this._MaSP != value))
				{
					if (this._QL_SanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSPChanging(value);
					this.SendPropertyChanging();
					this._MaSP = value;
					this.SendPropertyChanged("MaSP");
					this.OnMaSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soluong", DbType="Int")]
		public System.Nullable<int> Soluong
		{
			get
			{
				return this._Soluong;
			}
			set
			{
				if ((this._Soluong != value))
				{
					this.OnSoluongChanging(value);
					this.SendPropertyChanging();
					this._Soluong = value;
					this.SendPropertyChanged("Soluong");
					this.OnSoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Int")]
		public System.Nullable<int> DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_HoaDon_BanHang_QL_ChiTietHoaDon", Storage="_QL_HoaDon_BanHang", ThisKey="MaHD", OtherKey="MaHD", IsForeignKey=true)]
		public QL_HoaDon_BanHang QL_HoaDon_BanHang
		{
			get
			{
				return this._QL_HoaDon_BanHang.Entity;
			}
			set
			{
				QL_HoaDon_BanHang previousValue = this._QL_HoaDon_BanHang.Entity;
				if (((previousValue != value) 
							|| (this._QL_HoaDon_BanHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QL_HoaDon_BanHang.Entity = null;
						previousValue.QL_ChiTietHoaDons.Remove(this);
					}
					this._QL_HoaDon_BanHang.Entity = value;
					if ((value != null))
					{
						value.QL_ChiTietHoaDons.Add(this);
						this._MaHD = value.MaHD;
					}
					else
					{
						this._MaHD = default(string);
					}
					this.SendPropertyChanged("QL_HoaDon_BanHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_SanPham_QL_ChiTietHoaDon", Storage="_QL_SanPham", ThisKey="MaSP", OtherKey="MaSP", IsForeignKey=true)]
		public QL_SanPham QL_SanPham
		{
			get
			{
				return this._QL_SanPham.Entity;
			}
			set
			{
				QL_SanPham previousValue = this._QL_SanPham.Entity;
				if (((previousValue != value) 
							|| (this._QL_SanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QL_SanPham.Entity = null;
						previousValue.QL_ChiTietHoaDons.Remove(this);
					}
					this._QL_SanPham.Entity = value;
					if ((value != null))
					{
						value.QL_ChiTietHoaDons.Add(this);
						this._MaSP = value.MaSP;
					}
					else
					{
						this._MaSP = default(string);
					}
					this.SendPropertyChanged("QL_SanPham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QL_HoaDon_BanHang")]
	public partial class QL_HoaDon_BanHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHD;
		
		private string _MaND;
		
		private string _SDT;
		
		private System.Nullable<System.DateTime> _NgayLap;
		
		private string _PhuongThuc;
		
		private System.Nullable<int> _TienDua;
		
		private System.Nullable<int> _TienThua;
		
		private System.Nullable<int> _TongCong;
		
		private EntitySet<QL_ChiTietHoaDon> _QL_ChiTietHoaDons;
		
		private EntityRef<QL_KHACHHANG> _QL_KHACHHANG;
		
		private EntityRef<QL_NguoiDung> _QL_NguoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHDChanging(string value);
    partial void OnMaHDChanged();
    partial void OnMaNDChanging(string value);
    partial void OnMaNDChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnNgayLapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayLapChanged();
    partial void OnPhuongThucChanging(string value);
    partial void OnPhuongThucChanged();
    partial void OnTienDuaChanging(System.Nullable<int> value);
    partial void OnTienDuaChanged();
    partial void OnTienThuaChanging(System.Nullable<int> value);
    partial void OnTienThuaChanged();
    partial void OnTongCongChanging(System.Nullable<int> value);
    partial void OnTongCongChanged();
    #endregion
		
		public QL_HoaDon_BanHang()
		{
			this._QL_ChiTietHoaDons = new EntitySet<QL_ChiTietHoaDon>(new Action<QL_ChiTietHoaDon>(this.attach_QL_ChiTietHoaDons), new Action<QL_ChiTietHoaDon>(this.detach_QL_ChiTietHoaDons));
			this._QL_KHACHHANG = default(EntityRef<QL_KHACHHANG>);
			this._QL_NguoiDung = default(EntityRef<QL_NguoiDung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHD", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHD
		{
			get
			{
				return this._MaHD;
			}
			set
			{
				if ((this._MaHD != value))
				{
					this.OnMaHDChanging(value);
					this.SendPropertyChanging();
					this._MaHD = value;
					this.SendPropertyChanged("MaHD");
					this.OnMaHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaND", DbType="NChar(10)")]
		public string MaND
		{
			get
			{
				return this._MaND;
			}
			set
			{
				if ((this._MaND != value))
				{
					if (this._QL_NguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNDChanging(value);
					this.SendPropertyChanging();
					this._MaND = value;
					this.SendPropertyChanged("MaND");
					this.OnMaNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NChar(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					if (this._QL_KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLap", DbType="Date")]
		public System.Nullable<System.DateTime> NgayLap
		{
			get
			{
				return this._NgayLap;
			}
			set
			{
				if ((this._NgayLap != value))
				{
					this.OnNgayLapChanging(value);
					this.SendPropertyChanging();
					this._NgayLap = value;
					this.SendPropertyChanged("NgayLap");
					this.OnNgayLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhuongThuc", DbType="NVarChar(50)")]
		public string PhuongThuc
		{
			get
			{
				return this._PhuongThuc;
			}
			set
			{
				if ((this._PhuongThuc != value))
				{
					this.OnPhuongThucChanging(value);
					this.SendPropertyChanging();
					this._PhuongThuc = value;
					this.SendPropertyChanged("PhuongThuc");
					this.OnPhuongThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienDua", DbType="Int")]
		public System.Nullable<int> TienDua
		{
			get
			{
				return this._TienDua;
			}
			set
			{
				if ((this._TienDua != value))
				{
					this.OnTienDuaChanging(value);
					this.SendPropertyChanging();
					this._TienDua = value;
					this.SendPropertyChanged("TienDua");
					this.OnTienDuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienThua", DbType="Int")]
		public System.Nullable<int> TienThua
		{
			get
			{
				return this._TienThua;
			}
			set
			{
				if ((this._TienThua != value))
				{
					this.OnTienThuaChanging(value);
					this.SendPropertyChanging();
					this._TienThua = value;
					this.SendPropertyChanged("TienThua");
					this.OnTienThuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongCong", DbType="Int")]
		public System.Nullable<int> TongCong
		{
			get
			{
				return this._TongCong;
			}
			set
			{
				if ((this._TongCong != value))
				{
					this.OnTongCongChanging(value);
					this.SendPropertyChanging();
					this._TongCong = value;
					this.SendPropertyChanged("TongCong");
					this.OnTongCongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_HoaDon_BanHang_QL_ChiTietHoaDon", Storage="_QL_ChiTietHoaDons", ThisKey="MaHD", OtherKey="MaHD")]
		public EntitySet<QL_ChiTietHoaDon> QL_ChiTietHoaDons
		{
			get
			{
				return this._QL_ChiTietHoaDons;
			}
			set
			{
				this._QL_ChiTietHoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_KHACHHANG_QL_HoaDon_BanHang", Storage="_QL_KHACHHANG", ThisKey="SDT", OtherKey="SDT", IsForeignKey=true)]
		public QL_KHACHHANG QL_KHACHHANG
		{
			get
			{
				return this._QL_KHACHHANG.Entity;
			}
			set
			{
				QL_KHACHHANG previousValue = this._QL_KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._QL_KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QL_KHACHHANG.Entity = null;
						previousValue.QL_HoaDon_BanHangs.Remove(this);
					}
					this._QL_KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.QL_HoaDon_BanHangs.Add(this);
						this._SDT = value.SDT;
					}
					else
					{
						this._SDT = default(string);
					}
					this.SendPropertyChanged("QL_KHACHHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_NguoiDung_QL_HoaDon_BanHang", Storage="_QL_NguoiDung", ThisKey="MaND", OtherKey="MaND", IsForeignKey=true)]
		public QL_NguoiDung QL_NguoiDung
		{
			get
			{
				return this._QL_NguoiDung.Entity;
			}
			set
			{
				QL_NguoiDung previousValue = this._QL_NguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._QL_NguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QL_NguoiDung.Entity = null;
						previousValue.QL_HoaDon_BanHangs.Remove(this);
					}
					this._QL_NguoiDung.Entity = value;
					if ((value != null))
					{
						value.QL_HoaDon_BanHangs.Add(this);
						this._MaND = value.MaND;
					}
					else
					{
						this._MaND = default(string);
					}
					this.SendPropertyChanged("QL_NguoiDung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QL_ChiTietHoaDons(QL_ChiTietHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.QL_HoaDon_BanHang = this;
		}
		
		private void detach_QL_ChiTietHoaDons(QL_ChiTietHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.QL_HoaDon_BanHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QL_LoaiSanPham")]
	public partial class QL_LoaiSanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLoaiSP;
		
		private string _TenLoai;
		
		private string _GhiChu;
		
		private EntitySet<QL_SanPham> _QL_SanPhams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiSPChanging(string value);
    partial void OnMaLoaiSPChanged();
    partial void OnTenLoaiChanging(string value);
    partial void OnTenLoaiChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public QL_LoaiSanPham()
		{
			this._QL_SanPhams = new EntitySet<QL_SanPham>(new Action<QL_SanPham>(this.attach_QL_SanPhams), new Action<QL_SanPham>(this.detach_QL_SanPhams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiSP", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLoaiSP
		{
			get
			{
				return this._MaLoaiSP;
			}
			set
			{
				if ((this._MaLoaiSP != value))
				{
					this.OnMaLoaiSPChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiSP = value;
					this.SendPropertyChanged("MaLoaiSP");
					this.OnMaLoaiSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoai", DbType="NVarChar(50)")]
		public string TenLoai
		{
			get
			{
				return this._TenLoai;
			}
			set
			{
				if ((this._TenLoai != value))
				{
					this.OnTenLoaiChanging(value);
					this.SendPropertyChanging();
					this._TenLoai = value;
					this.SendPropertyChanged("TenLoai");
					this.OnTenLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NChar(10)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_LoaiSanPham_QL_SanPham", Storage="_QL_SanPhams", ThisKey="MaLoaiSP", OtherKey="MaLoaiSP")]
		public EntitySet<QL_SanPham> QL_SanPhams
		{
			get
			{
				return this._QL_SanPhams;
			}
			set
			{
				this._QL_SanPhams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QL_SanPhams(QL_SanPham entity)
		{
			this.SendPropertyChanging();
			entity.QL_LoaiSanPham = this;
		}
		
		private void detach_QL_SanPhams(QL_SanPham entity)
		{
			this.SendPropertyChanging();
			entity.QL_LoaiSanPham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QL_SanPham")]
	public partial class QL_SanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSP;
		
		private string _TenSanPham;
		
		private string _TinhTrang;
		
		private System.Nullable<int> _Gia;
		
		private string _Hinh;
		
		private string _MaLoaiSP;
		
		private EntitySet<QL_ChiTietHoaDon> _QL_ChiTietHoaDons;
		
		private EntityRef<QL_LoaiSanPham> _QL_LoaiSanPham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSPChanging(string value);
    partial void OnMaSPChanged();
    partial void OnTenSanPhamChanging(string value);
    partial void OnTenSanPhamChanged();
    partial void OnTinhTrangChanging(string value);
    partial void OnTinhTrangChanged();
    partial void OnGiaChanging(System.Nullable<int> value);
    partial void OnGiaChanged();
    partial void OnHinhChanging(string value);
    partial void OnHinhChanged();
    partial void OnMaLoaiSPChanging(string value);
    partial void OnMaLoaiSPChanged();
    #endregion
		
		public QL_SanPham()
		{
			this._QL_ChiTietHoaDons = new EntitySet<QL_ChiTietHoaDon>(new Action<QL_ChiTietHoaDon>(this.attach_QL_ChiTietHoaDons), new Action<QL_ChiTietHoaDon>(this.detach_QL_ChiTietHoaDons));
			this._QL_LoaiSanPham = default(EntityRef<QL_LoaiSanPham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSP", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSP
		{
			get
			{
				return this._MaSP;
			}
			set
			{
				if ((this._MaSP != value))
				{
					this.OnMaSPChanging(value);
					this.SendPropertyChanging();
					this._MaSP = value;
					this.SendPropertyChanged("MaSP");
					this.OnMaSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSanPham", DbType="NVarChar(50)")]
		public string TenSanPham
		{
			get
			{
				return this._TenSanPham;
			}
			set
			{
				if ((this._TenSanPham != value))
				{
					this.OnTenSanPhamChanging(value);
					this.SendPropertyChanging();
					this._TenSanPham = value;
					this.SendPropertyChanged("TenSanPham");
					this.OnTenSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="NVarChar(50)")]
		public string TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Int")]
		public System.Nullable<int> Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hinh", DbType="NVarChar(50)")]
		public string Hinh
		{
			get
			{
				return this._Hinh;
			}
			set
			{
				if ((this._Hinh != value))
				{
					this.OnHinhChanging(value);
					this.SendPropertyChanging();
					this._Hinh = value;
					this.SendPropertyChanged("Hinh");
					this.OnHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiSP", DbType="NChar(10)")]
		public string MaLoaiSP
		{
			get
			{
				return this._MaLoaiSP;
			}
			set
			{
				if ((this._MaLoaiSP != value))
				{
					if (this._QL_LoaiSanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiSPChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiSP = value;
					this.SendPropertyChanged("MaLoaiSP");
					this.OnMaLoaiSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_SanPham_QL_ChiTietHoaDon", Storage="_QL_ChiTietHoaDons", ThisKey="MaSP", OtherKey="MaSP")]
		public EntitySet<QL_ChiTietHoaDon> QL_ChiTietHoaDons
		{
			get
			{
				return this._QL_ChiTietHoaDons;
			}
			set
			{
				this._QL_ChiTietHoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_LoaiSanPham_QL_SanPham", Storage="_QL_LoaiSanPham", ThisKey="MaLoaiSP", OtherKey="MaLoaiSP", IsForeignKey=true)]
		public QL_LoaiSanPham QL_LoaiSanPham
		{
			get
			{
				return this._QL_LoaiSanPham.Entity;
			}
			set
			{
				QL_LoaiSanPham previousValue = this._QL_LoaiSanPham.Entity;
				if (((previousValue != value) 
							|| (this._QL_LoaiSanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QL_LoaiSanPham.Entity = null;
						previousValue.QL_SanPhams.Remove(this);
					}
					this._QL_LoaiSanPham.Entity = value;
					if ((value != null))
					{
						value.QL_SanPhams.Add(this);
						this._MaLoaiSP = value.MaLoaiSP;
					}
					else
					{
						this._MaLoaiSP = default(string);
					}
					this.SendPropertyChanged("QL_LoaiSanPham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QL_ChiTietHoaDons(QL_ChiTietHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.QL_SanPham = this;
		}
		
		private void detach_QL_ChiTietHoaDons(QL_ChiTietHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.QL_SanPham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QL_NguoiDung")]
	public partial class QL_NguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaND;
		
		private string _Password;
		
		private string _TenNguoiDung;
		
		private string _SoDienThoai;
		
		private string _HoatDong;
		
		private EntitySet<QL_HoaDon_BanHang> _QL_HoaDon_BanHangs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNDChanging(string value);
    partial void OnMaNDChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnTenNguoiDungChanging(string value);
    partial void OnTenNguoiDungChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnHoatDongChanging(string value);
    partial void OnHoatDongChanged();
    #endregion
		
		public QL_NguoiDung()
		{
			this._QL_HoaDon_BanHangs = new EntitySet<QL_HoaDon_BanHang>(new Action<QL_HoaDon_BanHang>(this.attach_QL_HoaDon_BanHangs), new Action<QL_HoaDon_BanHang>(this.detach_QL_HoaDon_BanHangs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaND", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaND
		{
			get
			{
				return this._MaND;
			}
			set
			{
				if ((this._MaND != value))
				{
					this.OnMaNDChanging(value);
					this.SendPropertyChanging();
					this._MaND = value;
					this.SendPropertyChanged("MaND");
					this.OnMaNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNguoiDung", DbType="NVarChar(50)")]
		public string TenNguoiDung
		{
			get
			{
				return this._TenNguoiDung;
			}
			set
			{
				if ((this._TenNguoiDung != value))
				{
					this.OnTenNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._TenNguoiDung = value;
					this.SendPropertyChanged("TenNguoiDung");
					this.OnTenNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="NChar(11)")]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoatDong", DbType="NChar(10)")]
		public string HoatDong
		{
			get
			{
				return this._HoatDong;
			}
			set
			{
				if ((this._HoatDong != value))
				{
					this.OnHoatDongChanging(value);
					this.SendPropertyChanging();
					this._HoatDong = value;
					this.SendPropertyChanged("HoatDong");
					this.OnHoatDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_NguoiDung_QL_HoaDon_BanHang", Storage="_QL_HoaDon_BanHangs", ThisKey="MaND", OtherKey="MaND")]
		public EntitySet<QL_HoaDon_BanHang> QL_HoaDon_BanHangs
		{
			get
			{
				return this._QL_HoaDon_BanHangs;
			}
			set
			{
				this._QL_HoaDon_BanHangs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QL_HoaDon_BanHangs(QL_HoaDon_BanHang entity)
		{
			this.SendPropertyChanging();
			entity.QL_NguoiDung = this;
		}
		
		private void detach_QL_HoaDon_BanHangs(QL_HoaDon_BanHang entity)
		{
			this.SendPropertyChanging();
			entity.QL_NguoiDung = null;
		}
	}
}
#pragma warning restore 1591
