//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL_DAL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-AN0VONI\\SQLEXPRESS;Initial Catalog=DAMN_CuaHangThucAnNhanh;Us" +
            "er ID=sa;Password =sa2012")]
        public string DAMN_CuaHangThucAnNhanhConnectionString {
            get {
                return ((string)(this["DAMN_CuaHangThucAnNhanhConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-AN0VONI\\SQLEXPRESS;Initial Catalog=DAMN_CuaHangThucAnNhanh;Us" +
            "er ID=sa;Password=sa2012")]
        public string DAMN_CuaHangThucAnNhanhConnectionString1 {
            get {
                return ((string)(this["DAMN_CuaHangThucAnNhanhConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-AN0VONI\\SQLEXPRESS;Initial Catalog=DAMN_QuanLyCaPhe;User ID=s" +
            "a;Password=sa2012")]
        public string DAMN_QuanLyCaPheConnectionString {
            get {
                return ((string)(this["DAMN_QuanLyCaPheConnectionString"]));
            }
        }
    }
}
